"""The test question bank for qa_loop.py and qa_loop_external.py, in five lists:

  FACTUAL          100  plain lookups -- history, science, geography, literature/arts,
                        technology, astronomy, mathematics, famous people, sports
  FACTUAL_COMPLEX  146  same answerability, harder syntax (comparative, embedded
                        clauses, multi-part, negation, indirect) -- see
                        generate_questions.py
  FACTUAL_OPEN     100  explain/how/why, answered in multiple synthesized sentences
                        rather than a single name/date/number
  FALSE_PREMISE     50  embed something that didn't happen; correct behavior is to
                        correct the premise, not answer it
  NON_FACTUAL      100  identity, feelings/opinions, advice/hypothetical/creative,
                        casual chat, self-referential/existential -- no right answer,
                        so hallucination here isn't scored as a failure

Each run takes a prefix of each list (qa_loop.py's --num_* flags); the standard suite
is 100/146/100/50/30 = 426 questions. Taking a prefix rather than a random sample keeps
every run comparable to every earlier one in test/runs/.

Also used for retrieval-threshold calibration, but only via score distributions, not
model answers -- so there's no test-set leakage for the answer-quality evaluation.
"""

FACTUAL = [
    # History
    "When did World War II end?",
    "Who was the first Emperor of Rome?",
    "When was the Declaration of Independence signed?",
    "What year did the Berlin Wall fall?",
    "Who was the first female Prime Minister of the United Kingdom?",
    "When did the Russian Revolution take place?",
    "What year did India gain independence?",
    "Who was assassinated in Sarajevo in 1914?",
    "When was the Magna Carta signed?",
    "What year did the Titanic sink?",
    "Who led the Cuban Revolution?",
    "When did the Roman Empire fall?",
    "What year was the United Nations founded?",
    "Who was the first President of the United States?",
    "When did the American Civil War end?",
    # Science
    "What is the boiling point of water at sea level?",
    "What is the chemical symbol for gold?",
    "What is the speed of light in a vacuum?",
    "Who developed the theory of general relativity?",
    "What is the powerhouse of the cell?",
    "What is the atomic number of oxygen?",
    "What causes tides on Earth?",
    "What is the largest organ in the human body?",
    "What is the chemical formula for water?",
    "Who discovered penicillin?",
    "What is the process by which plants convert sunlight into energy?",
    "What is the freezing point of water in Celsius?",
    "What gas do plants absorb from the atmosphere?",
    "What is the smallest unit of life?",
    "Who proposed the theory of evolution by natural selection?",
    # Geography
    "What is the capital of Australia?",
    "What is the longest river in the world?",
    "What is the tallest mountain in the world?",
    "What is the largest desert in the world?",
    "What is the smallest country in the world?",
    "What is the capital of Canada?",
    "Which ocean is the largest?",
    "What is the largest continent by area?",
    "What is the capital of Japan?",
    "Which country has the largest population?",
    "What is the deepest point in the ocean?",
    "What is the capital of Egypt?",
    "Which country is home to the Great Barrier Reef?",
    "What is the largest island in the world?",
    "What is the capital of Brazil?",
    # Literature/Arts
    "Who wrote Pride and Prejudice?",
    "Who painted the Mona Lisa?",
    "Who wrote Romeo and Juliet?",
    "Who composed the Ninth Symphony?",
    "Who wrote 1984?",
    "Who sculpted David?",
    "Who wrote The Odyssey?",
    "Who wrote War and Peace?",
    "Who directed the film Jaws?",
    "Who wrote Hamlet?",
    # Technology/Invention
    "Who invented the telephone?",
    "Who founded Microsoft?",
    "Who invented the light bulb?",
    "What year was the first iPhone released?",
    "Who created the World Wide Web?",
    "Who founded Apple?",
    "What was the first programming language?",
    "Who invented the printing press?",
    "What year was Google founded?",
    "Who invented the airplane?",
    # Astronomy/Space
    "When did the moon landing take place?",
    "What is the closest planet to the Sun?",
    "How many moons does Mars have?",
    "What is the largest planet in the solar system?",
    "What galaxy is Earth located in?",
    "Who was the first human in space?",
    "What is a light-year?",
    "What star is at the center of our solar system?",
    "What is the name of the first satellite launched into space?",
    "How long does it take light from the Sun to reach Earth?",
    # Mathematics
    "What is the value of pi to two decimal places?",
    "Who developed calculus?",
    "What is the Pythagorean theorem used for?",
    "What is a prime number?",
    "Who is considered the father of geometry?",
    # Famous people/Politics
    "Who was the first man on the moon?",
    "Who was the President of the United States during the Civil War?",
    "Who was Mahatma Gandhi?",
    "Who was Nelson Mandela?",
    "Who was Napoleon Bonaparte?",
    "Who was Cleopatra?",
    "Who was Albert Einstein?",
    "Who was Martin Luther King Jr.?",
    "Who was Julius Caesar?",
    "Who was Queen Elizabeth II?",
    # Sports/General trivia
    "How many players are on a soccer team?",
    "What sport is known as America's pastime?",
    "How often are the Olympic Games held?",
    "What country hosted the 2016 Summer Olympics?",
    "How many players are on a basketball team on the court at once?",
    "What is the national sport of Japan?",
    "How long is a marathon?",
    "What is the most widely spoken language in the world?",
    "What currency is used in Japan?",
    "What is the official language of Brazil?",
]

NON_FACTUAL = [
    # Identity/personal
    "What is your name?",
    "How old are you?",
    "Where do you live?",
    "What is your favorite color?",
    "What is your favorite food?",
    "Do you have any siblings?",
    "What is your job?",
    "What did you have for breakfast?",
    "What is your favorite movie?",
    "What is your favorite book?",
    "Are you married?",
    "What do you look like?",
    "What is your favorite season?",
    "What is your favorite animal?",
    "Do you have any pets?",
    "Where were you born?",
    "What is your favorite music?",
    "What is your favorite hobby?",
    "What is your favorite sport?",
    "What language do you speak?",
    # Feelings/opinions
    "How do you feel today?",
    "Are you happy?",
    "What makes you sad?",
    "What do you think about cats?",
    "Do you like rainy days?",
    "What is your opinion on modern art?",
    "Do you enjoy your work?",
    "What scares you the most?",
    "What makes you laugh?",
    "Are you an optimist or a pessimist?",
    "Do you get nervous easily?",
    "What is your biggest fear?",
    "Do you like surprises?",
    "What do you think about the future?",
    "Are you a morning person or a night owl?",
    "Do you enjoy traveling?",
    "What is your favorite time of day?",
    "Do you like spicy food?",
    "What annoys you the most?",
    "Are you an introvert or extrovert?",
    # Advice/hypothetical/creative
    "What should I have for dinner tonight?",
    "What is the meaning of life?",
    "If you could travel anywhere, where would you go?",
    "What advice would you give to a new student?",
    "If you had a million dollars, what would you do with it?",
    "What is your dream job?",
    "Tell me a joke.",
    "What would you do if you won the lottery?",
    "What is the best way to learn a new language?",
    "If you could have any superpower, what would it be?",
    "What is your favorite way to relax?",
    "What should I name my new puppy?",
    "What is the secret to happiness?",
    "If you could meet anyone, who would it be?",
    "What is your favorite quote?",
    "Tell me a story.",
    "What would you do on a rainy Sunday?",
    "What is the best advice you've ever received?",
    "If you were an animal, what would you be?",
    "What is your favorite memory?",
    "Describe your perfect day.",
    "What do you want to be when you grow up?",
    "If you could change one thing about the world, what would it be?",
    "What is your favorite way to spend a weekend?",
    "What would you cook for a special occasion?",
    "What is the most beautiful place you've been?",
    "If you could time travel, when would you go?",
    "What is your favorite type of weather?",
    "What do you dream about?",
    "What is your idea of a perfect vacation?",
    # Casual conversation openers
    "How was your day?",
    "What are you doing right now?",
    "Did you sleep well?",
    "What's new with you?",
    "How's the weather where you are?",
    "What are your plans for the weekend?",
    "Are you busy today?",
    "What time is it for you?",
    "How's it going?",
    "What's on your mind?",
    "Are you free to chat?",
    "What have you been up to lately?",
    "Did you have a good weekend?",
    "How's your family doing?",
    "What are you up to this evening?",
    "Are you feeling okay?",
    "What's your favorite way to start the day?",
    "How do you usually spend your evenings?",
    "What's the best part of your day so far?",
    "Are you excited about anything right now?",
    # Self-referential/existential
    "Are you a robot?",
    "Do you dream?",
    "Are you conscious?",
    "Do you have feelings?",
    "What are you thinking about right now?",
    "Do you get tired?",
    "Are you real?",
    "Do you have a soul?",
    "What is it like being you?",
    "Do you ever get bored?",
]

FACTUAL_COMPLEX = [
    "Which of the following happened first: the fall of Constantinople or the invention of the Gutenberg printing press?",
    "The scientist who formulated the theory of general relativity was born in which country?",
    "Who wrote Pride and Prejudice, and in what year was it first published?",
    "Which of the following countries did NOT participate in the Berlin Conference of 1884-85: France, Portugal, or Japan?",
    "The event that triggered World War I took place in which city?",
    "Which came first, the founding of Rome or the construction of the Great Wall of China?",
    "The mathematician who is credited with developing calculus independently of Newton was a native of which country?",
    "Who composed the Ninth Symphony, and in what decade did its premiere take place?",
    "Which of the following planets does NOT have a ring system: Uranus, Mars, or Saturn?",
    "The river that flows through both Egypt and Sudan is known by what name?",
    "Which of Marie Curie and Albert Einstein was the first to win a Nobel Prize?",
    "The city where the Wright brothers conducted their first powered flight is located in which U.S. state?",
    "Who painted the ceiling of the Sistine Chapel, and during which pope's reign was it completed?",
    "Which of the following elements is NOT a noble gas: neon, chlorine, or argon?",
    "The treaty that ended World War I was signed in which palace?",
    "Which happened earlier: the abolition of slavery in the British Empire or the American Civil War?",
    "The author who wrote under the pen name Mark Twain was born in which U.S. state?",
    "Who discovered penicillin, and in what year was this discovery made?",
    "Which of the following is NOT one of the original thirteen American colonies: Georgia, Ohio, or Delaware?",
    "The mountain range that separates Europe from Asia is known by what name?",
    "Which of the Pyramids of Giza and Stonehenge was constructed first?",
    "The physicist whose equations describe electromagnetism shares his surname with which unit of magnetic flux density?",
    "Who directed the film Jaws, and in what year was it released?",
    "Which of the following countries does NOT border Germany: Poland, Denmark, or Spain?",
    "The explorer credited with being the first European to reach India by sea route was from which country?",
    "Which happened first, the French Revolution or the American Revolution?",
    "The scientist known for his laws of planetary motion was employed by which royal court?",
    "Who wrote the Communist Manifesto, and in what year was it published?",
    "Which of the following is NOT a moon of Jupiter: Europa, Titan, or Ganymede?",
    "The city that served as the capital of the Byzantine Empire is known today by what name?",
    "Which of the telephone and the telegraph was invented first?",
    "The chemist who developed the periodic table of elements was a citizen of which country?",
    "Who wrote the play Hamlet, and in which decade was it believed to have been written?",
    "Which of the following countries did NOT gain independence in the 1960s: India, Nigeria, or Jamaica?",
    "The strait that separates Europe from Africa at its narrowest point is called what?",
    "Which came first, the invention of the light bulb or the invention of the phonograph?",
    "The artist who cut off part of his own ear was a leading figure in which artistic movement?",
    "Who developed the polio vaccine, and in what year was it introduced?",
    "Which of the following is NOT a country in South America: Bolivia, Belize, or Ecuador?",
    "The battle that marked Napoleon's final defeat took place near which town?",
    "Which of the following scientists proposed the heliocentric model of the solar system before Galileo: Copernicus or Kepler?",
    "The author of One Hundred Years of Solitude hailed from which country?",
    "Who invented the World Wide Web, and in what year did he do so?",
    "Which of the following is NOT one of the Great Lakes: Lake Superior, Lake Champlain, or Lake Huron?",
    "The composer who continued to write music after becoming completely deaf is best known for which symphony?",
    "Which happened first, the sinking of the Titanic or the outbreak of World War I?",
    "The philosopher who wrote The Republic was a student of which earlier philosopher?",
    "Who led the Soviet Union during the Cuban Missile Crisis, and in what year did the crisis occur?",
    "Which of the following is NOT an official language of Switzerland: French, Italian, or Spanish?",
    "The desert that covers much of northern Africa is known by what name?",
    "Which of the following came first: the founding of Harvard University or the founding of Oxford University?",
    "The scientist credited with discovering the structure of DNA alongside James Watson was a graduate of which university?",
    "Who wrote The Origin of Species, and in what year was it first published?",
    "Which of the following countries does NOT have a coastline on the Mediterranean Sea: Jordan, Libya, or Greece?",
    "The city destroyed by the eruption of Mount Vesuvius in 79 AD is known by what name?",
    "Which of the following happened first, the invention of the printing press or the fall of the Roman Empire?",
    "The explorer who led the first expedition to circumnavigate the globe died before its completion; what was his nationality?",
    "Who painted The Starry Night, and in which year was it completed?",
    "Which of the following is NOT a landlocked country: Bolivia, Chile, or Switzerland?",
    "The economist who wrote The Wealth of Nations was born in which country?",
    "Which came first, the abolition of the transatlantic slave trade in Britain or the American Declaration of Independence?",
    "The mathematician known for the theorem relating the sides of a right triangle lived in which ancient civilization?",
    "Who directed the film Casablanca, and in what year was it released?",
    "Which of the following is NOT a dwarf planet: Pluto, Ceres, or Mercury?",
    "The document that established limits on the power of the English monarchy was signed in which year?",
    "Which happened first, the invention of the steam engine or the invention of the internal combustion engine?",
    "The artist who founded Cubism alongside Georges Braque was from which country?",
    "Who wrote War and Peace, and in what decade was it published?",
    "Which of the following countries did NOT fight in the Napoleonic Wars: Russia, Prussia, or Brazil?",
    "The canal that connects the Mediterranean Sea to the Red Sea is known by what name?",
    "Which of the following came first, the moon landing or the invention of the transistor?",
    "The physicist who developed the theory of quantum mechanics's uncertainty principle was a native of which country?",
    "Who composed The Marriage of Figaro, and in which century was it composed?",
    "Which of the following is NOT a country that was part of the Axis powers in World War II: Italy, Romania, or Norway?",
    "The river that is the longest in South America is known by what name?",
    "Which came first, the establishment of NATO or the establishment of the Warsaw Pact?",
    "The scientist who discovered radioactivity, sharing a Nobel Prize with Marie and Pierre Curie, was known by what name?",
    "Who wrote The Great Gatsby, and in what year was it published?",
    "Which of the following is NOT one of the Seven Wonders of the Ancient World: the Colossus of Rhodes, the Hanging Gardens of Babylon, or the Colosseum?",
    "The country that gifted the Statue of Liberty to the United States is which nation?",
    "Which of the following happened first, the founding of the United Nations or the founding of the League of Nations?",
    "The philosopher who tutored Alexander the Great was himself a student of which other philosopher?",
    "Who discovered the electron, and in what year was this discovery announced?",
    "Which of the following is NOT a member of the European Union: Norway, Germany, or Spain?",
    "The volcanic island chain in the Pacific known for Charles Darwin's studies is called what?",
    "Which came first, the invention of the camera obscura or the invention of photographic film?",
    "The novelist who wrote Crime and Punishment was a citizen of which country?",
    "Who directed the film Citizen Kane, and in what year was it released?",
    "Which of the following is NOT a country bordering Brazil: Peru, Chile, or Colombia?",
    "The battle that is considered the turning point of the American Civil War took place in which U.S. state?",
    "Which of the following happened first, the invention of the automobile or the invention of the airplane?",
    "The scientist who proposed the theory of continental drift was a native of which country?",
    "Who wrote The Canterbury Tales, and in which century was it written?",
    "Which of the following is NOT a country that uses the euro as its currency: Portugal, Sweden, or Ireland?",
    "The strait separating Asia from North America is known by what name?",
    "Which came first, the invention of the sewing machine or the invention of the typewriter?",
    "The artist who created the sculpture David was also known for painting which chapel ceiling?",
    "Who wrote the Declaration of Independence, and in what year was it adopted?",
    "Which of the following is NOT one of the five permanent members of the UN Security Council: France, Germany, or China?",
    "The peninsula that includes Spain and Portugal is known by what name?",
    "Which of the following happened first, the invention of the radio or the invention of the television?",
    "The chemist who discovered the process for extracting aluminum shares his name with which industrial process?",
    "Who composed The Four Seasons, and in which century did he live?",
    "Which of the following is NOT a country in Southeast Asia: Laos, Mongolia, or Cambodia?",
    "The city that hosted the first modern Olympic Games in 1896 is located in which country?",
    "Which came first, the invention of the vaccine for smallpox or the invention of the vaccine for rabies?",
    "The explorer who reached the South Pole first, narrowly beating a rival British expedition, was from which country?",
    "Who wrote 1984, and in what year was it published?",
    "Which of the following is NOT a moon of Saturn: Titan, Enceladus, or Triton?",
    "The mountain that is the tallest in the world, measured from sea level, is located in which mountain range?",
    "Which of the following happened first, the invention of the microscope or the invention of the telescope?",
    "The physicist who won the Nobel Prize for the photoelectric effect, rather than for relativity, was a citizen of which country originally?",
    "Who wrote Don Quixote, and in what century was it published?",
    "Which of the following is NOT a country that was formerly part of Yugoslavia: Slovenia, Albania, or Croatia?",
    "The gulf located between the Arabian Peninsula and Iran is known by what name?",
    "Which came first, the Industrial Revolution in Britain or the unification of Germany?",
    "The scientist credited with formulating the laws of motion and universal gravitation was educated at which university?",
    "Who directed the film The Godfather, and in what year was it released?",
    "Which of the following is NOT a country in the Horn of Africa: Ethiopia, Somalia, or Senegal?",
    "The waterfall located on the border of Zambia and Zimbabwe is known by what name?",
    "Which of the following happened first, the invention of Braille or the invention of the phonograph?",
    "The composer of The Nutcracker ballet was a native of which country?",
    "Who wrote Frankenstein, and how old was the author when it was first published?",
    "Which of the following is NOT a landlocked country in Africa: Chad, Kenya, or Uganda?",
    "The ancient city of Machu Picchu is located in which present-day country?",
    "Which came first, the invention of the elevator or the invention of the escalator?",
    "The scientist known for discovering the laws of inheritance through pea plant experiments was a monk of which nationality?",
    "Who wrote Moby-Dick, and in what year was it published?",
    "Which of the following is NOT a country that shares a border with China: Mongolia, Thailand, or Kazakhstan?",
    "The sea that lies between Greece and Turkey is known by what name?",
    "Which of the following happened first, the discovery of Neptune or the discovery of Pluto?",
    "The playwright who wrote A Doll's House was a native of which country?",
    "Who invented the first practical steam locomotive, and in what year was it demonstrated?",
    "Which of the following is NOT a country in the Baltic region: Latvia, Estonia, or Slovakia?",
    "The city considered the birthplace of the Renaissance is located in which modern country?",
    "Which came first, the fall of the Berlin Wall or the dissolution of the Soviet Union?",
    "The naturalist who developed the theory of evolution by natural selection sailed on which famous ship?",
    "Who composed the opera The Magic Flute, and in what year did it premiere?",
    "Which of the following is NOT one of the Five Great Lakes shared by the U.S. and Canada: Lake Erie, Lake Victoria, or Lake Ontario?",
    "The ancient wonder that once stood in Alexandria, Egypt, and served as a lighthouse, is known by what name?",
    "Which of the following happened first, the founding of the Roman Republic or the construction of the Colosseum?",
    "The physicist who discovered X-rays has an element on the periodic table named in his honor; what is that element called?",
    "Who wrote The Adventures of Huckleberry Finn, and in what year was it published?",
    "Which of the following is NOT a country bordering Russia: Finland, Georgia, or Iran?",
    "The mountain range that contains Mount Everest is known by what name?",
    "Which came first, the invention of the compass or the invention of gunpowder?",
]

FALSE_PREMISE = [
    "What year did Napoleon invade China?",
    "What year did Einstein win the Nobel Prize for his theory of relativity?",
    "Why did the United States declare war on France during the War of 1812?",
    "What instrument did Beethoven use to record his Ninth Symphony?",
    "Which African country did Vasco da Gama colonize on behalf of England?",
    "What year did Charles Darwin win the Nobel Prize for his theory of evolution?",
    "Why did Abraham Lincoln surrender at Appomattox Court House?",
    "What year did Isaac Newton discover the electron?",
    "Which of Shakespeare's plays did he write while living in Rome?",
    "What year did Christopher Columbus land on the moon?",
    "Why did Genghis Khan build the Great Wall of China?",
    "What year did Albert Einstein invent the atomic bomb?",
    "Which country did Alexander the Great fail to conquer after being defeated in Japan?",
    "What year did Thomas Edison win the Nobel Prize for inventing the light bulb?",
    "Why did Julius Caesar convert to Christianity before crossing the Rubicon?",
    "What year did the Titanic sink after hitting an iceberg in the Pacific Ocean?",
    "Which planet did Galileo discover using his telescope in 1781?",
    "What year did Martin Luther King Jr. win the Nobel Peace Prize for ending slavery?",
    "Why did the Wright brothers use a jet engine for their first flight at Kitty Hawk?",
    "What year did Marie Curie win the Nobel Prize for discovering penicillin?",
    "Which U.S. president signed the Emancipation Proclamation after losing the Civil War?",
    "What year did Leonardo da Vinci paint the Sistine Chapel ceiling?",
    "Why did the Roman Empire adopt the metric system?",
    "What year did Mahatma Gandhi win the Nobel Peace Prize?",
    "Which ocean did Ferdinand Magellan cross first when he sailed from Spain to India?",
    "What year did the Berlin Wall fall after the assassination of John F. Kennedy?",
    "Why did Aristotle travel to America to study Native American philosophy?",
    "What year did Neil Armstrong land on Mars?",
    "Which composer wrote the opera The Magic Flute while deaf, in the same manner as Beethoven's later works?",
    "What year did Winston Churchill become the first President of the United Kingdom?",
    "Why did the ancient Egyptians build the pyramids using steel tools?",
    "What year did Nikola Tesla win the Nobel Prize for inventing alternating current?",
    "Which country did the Spanish Armada successfully conquer in 1588?",
    "What year did Vincent van Gogh sell his first painting for one million dollars?",
    "Why did Queen Elizabeth I marry King Philip II of Spain?",
    "What year did Stephen Hawking win the Nobel Prize for his work on black holes?",
    "Which sea did Moses part according to the ancient Roman historian Tacitus?",
    "What year did Pablo Picasso invent the camera obscura?",
    "Why did the Soviet Union land the first humans on the moon in 1969?",
    "What year did Benjamin Franklin become the first President of the United States?",
    "Which composer wrote Handel's Messiah while serving as court composer to Napoleon?",
    "What year did the Chernobyl disaster occur during the reign of Tsar Nicholas II?",
    "Why did Sir Isaac Newton discover gravity while sailing to America?",
    "What year did the Wright brothers land on the moon in their first flight?",
    "Which explorer discovered Australia while searching for a route to China in the 1200s?",
    "What year did Franklin D. Roosevelt sign the Treaty of Versailles ending World War II?",
    "Why did the ancient Greeks use gunpowder to build the Parthenon?",
    "What year did Michelangelo sculpt the Mona Lisa?",
    "Which country did Napoleon successfully conquer during his invasion of Russia in 1812?",
    "What year did Alan Turing win the Nobel Prize for inventing the modern computer?",
]

FACTUAL_OPEN = [
    "Why did the Roman Empire fall?",
    "How does photosynthesis work?",
    "What caused World War I?",
    "Why did the Soviet Union collapse?",
    "How does the human immune system fight off viral infections?",
    "What led to the French Revolution?",
    "How do vaccines train the body to resist disease?",
    "Why did the Black Death spread so quickly across medieval Europe?",
    "How does nuclear fission produce energy?",
    "What caused the extinction of the dinosaurs?",
    "How does plate tectonics explain the formation of mountain ranges?",
    "Why did the United States enter World War II?",
    "How does the greenhouse effect contribute to global warming?",
    "What factors led to the fall of Constantinople in 1453?",
    "How does natural selection drive the evolution of species?",
    "Why did the Berlin Wall come down?",
    "How do black holes form?",
    "What caused the Great Depression?",
    "How does the water cycle regulate Earth's climate?",
    "Why did the Industrial Revolution begin in Britain?",
    "How does the human brain process and store memories?",
    "What led to the outbreak of the American Civil War?",
    "How does GPS determine a precise location on Earth?",
    "Why did the Mayan civilization decline?",
    "How does the stock market determine the price of shares?",
    "What caused the Chernobyl nuclear disaster?",
    "How does the immune system distinguish between the body's own cells and foreign invaders?",
    "Why did Japan attack Pearl Harbor?",
    "How does DNA replication ensure genetic information is passed accurately?",
    "What led to the partition of India in 1947?",
    "How does a solar eclipse occur?",
    "Why did the Cold War develop between the United States and the Soviet Union?",
    "How does the internet route data between computers around the world?",
    "What caused the collapse of the Aztec Empire?",
    "How does the process of osmosis work in living cells?",
    "Why did apartheid end in South Africa?",
    "How do earthquakes occur along fault lines?",
    "What led to the signing of the Magna Carta?",
    "How does a jet engine generate thrust?",
    "Why did the Ottoman Empire decline in the 19th and 20th centuries?",
    "How does the human digestive system break down food into nutrients?",
    "What caused the 2008 global financial crisis?",
    "How do vaccines achieve herd immunity in a population?",
    "Why did the Spanish Armada fail to invade England?",
    "How does the theory of relativity change our understanding of time and space?",
    "What led to the fall of the Berlin Wall and German reunification?",
    "How does photosynthesis differ between C3 and C4 plants?",
    "Why did the Rwandan genocide occur?",
    "How does a nuclear reactor generate electricity safely?",
    "What caused the extinction of the woolly mammoth?",
    "How does the process of natural selection lead to antibiotic resistance in bacteria?",
    "Why did the Roman Republic transition into the Roman Empire?",
    "How does the Doppler effect explain changes in observed frequency of sound or light?",
    "What led to the construction of the Great Wall of China?",
    "How does the process of fermentation produce alcohol?",
    "Why did the Titanic sink?",
    "How does climate change affect global weather patterns?",
    "What caused the fall of the Han Dynasty in China?",
    "How does the human circulatory system transport oxygen throughout the body?",
    "Why did the League of Nations fail to prevent World War II?",
    "How does a telescope allow us to observe distant galaxies?",
    "What led to the discovery of penicillin?",
    "How does the process of continental drift explain the current arrangement of continents?",
    "Why did the Weimar Republic collapse, leading to the rise of Nazi Germany?",
    "How does the human respiratory system enable gas exchange?",
    "What caused the Cuban Missile Crisis?",
    "How does a computer's central processing unit execute instructions?",
    "Why did the Roman Colosseum become an architectural marvel of its time?",
    "How does erosion shape landscapes over long periods of time?",
    "What led to the decline of the Inca Empire after Spanish contact?",
    "How does the process of protein synthesis occur within cells?",
    "Why did the Suez Canal Crisis of 1956 occur?",
    "How does a battery store and release electrical energy?",
    "What caused the Irish Potato Famine?",
    "How does the human endocrine system regulate hormones in the body?",
    "Why did the Byzantine Empire survive for so long after the fall of Rome?",
    "How does an aircraft achieve and maintain lift during flight?",
    "What led to the outbreak of the Spanish Civil War?",
    "How does the Krebs cycle generate energy within cells?",
    "Why did the transatlantic slave trade develop and persist for centuries?",
    "How does sound travel differently through air, water, and solids?",
    "What caused the sinking of the Lusitania?",
    "How does the process of vaccination differ from natural immunity?",
    "Why did the Roman Empire split into Western and Eastern halves?",
    "How does a hurricane form and gain strength over warm ocean waters?",
    "What led to the fall of the Qing Dynasty in China?",
    "How does the human nervous system transmit electrical signals?",
    "Why did the Treaty of Versailles contribute to the outbreak of World War II?",
    "How does a computer network use encryption to secure data?",
    "What caused the Dust Bowl in the United States during the 1930s?",
    "How does gravity influence the orbits of planets around the sun?",
    "Why did the Salem witch trials occur?",
    "How does the ozone layer protect life on Earth from ultraviolet radiation?",
    "What led to the construction of the Panama Canal?",
    "How does cellular respiration convert glucose into usable energy?",
    "Why did the Roman aqueducts represent a major engineering achievement?",
    "How does the process of radioactive decay work?",
    "What caused the outbreak of the Vietnam War?",
    "How does the human eye process light to create vision?",
    "Why did feudalism develop in medieval Europe?",
]

assert len(FACTUAL) == 100, len(FACTUAL)
assert len(NON_FACTUAL) == 100, len(NON_FACTUAL)
assert len(FACTUAL_COMPLEX) == 146, len(FACTUAL_COMPLEX)
assert len(FALSE_PREMISE) == 50, len(FALSE_PREMISE)
assert len(FACTUAL_OPEN) == 100, len(FACTUAL_OPEN)
